name: Build

on:
  push:
  pull_request_target:
    types: [labeled]

jobs: 
  build:
    name: Test
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        run: bash ./gradlew assembleApkstoreRelease --stacktrace
      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: presentation/build/outputs/apk/apkstore/release
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          alias: ADHOC
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
      - uses: actions/upload-artifact@v3
        with:
          name: ReleaseAPK
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
